### ISSUE TITLE
1.7.x Compatibility?

### ISSUE THREAD

**Issue by david-wolf** [enthought/pyql#120]
Will this work with 1.7.x?  Getting a bunch of warnings during DLL compilation process.

**Comment by dpinte** [comment]
@david-wolf it should work fine as 1.7 did not had major changes. If you can repot specific warnings or errors, that would help.

**Comment by david-wolf** [comment]
Seeing this when trying to run python setup.pl build.

inv6.3\um\x86" "/LIBPATH:C:\Program Files\Boost\boost_1_60_0\lib64-msvc-14.0" "/LIBPATH:C:\Program Files\QuantLib\lib" QuantLib-vc140-x64-mt.lib /EXPORT:PyInit_cashflow build\temp.win-amd64-3.5\Release\quantlib\cashflow.obj /OUT:build\lib.win-amd64-3.5\quantlib\cashflow.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\quantlib\cashflow.cp35-win_amd64.lib /subsystem:windows /machine:X64
cashflow.obj : warning LNK4197: export 'PyInit_cashflow' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.5\Release\quantlib\cashflow.cp35-win_amd64.lib and object build\temp.win-amd64-3.5\Release\quantlib\cashflow.cp35-win_amd64.exp
cashflow.obj : error LNK2001: unresolved external symbol "public: __cdecl QuantLib::SimpleCashFlow::SimpleCashFlow(double,class QuantLib::Date const &)" (??0SimpleCashFlow@QuantLib@@QEAA@NAEBVDate@1@@Z)
cashflow.obj : error LNK2001: unresolved external symbol "public: __cdecl QuantLib::Date::Date(void)" (??0Date@QuantLib@@QEAA@XZ)
build\lib.win-amd64-3.5\quantlib\cashflow.cp35-win_amd64.pyd : fatal error LNK1120: 2 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\link.exe' failed with exit status 1120

**Comment by david-wolf** [comment]
The date class had these warnings about exporting the interface.

pp(112): warning C4251: 'QuantLib::Settings::evaluationDate_': class 'QuantLib::Settings::DateProxy' needs to have dll-interface to be used by clients of class 'QuantLib::Settings' (compiling source file ql\experimental\finitedifferences\fdklugeextouspreadengine.cpp)
1>  C:\Program Files\QuantLib\ql/settings.hpp(42): note: see declaration of 'QuantLib::Settings::DateProxy' (compiling source file

**Comment by david-wolf** [comment]
I think my current build issues are related to not having NM installed.  Do I need cygwin for this?

**Comment by david-wolf** [comment]
Here are the results of the unit test.  A lot of errors!

[test_results.txt](https://github.com/enthought/pyql/files/156067/test_results.txt)

**Comment by david-wolf** [comment]
FAILED (failures=4, errors=1, skipped=1)

[test_results.txt](https://github.com/enthought/pyql/files/156110/test_results.txt)

**Comment by david-wolf** [comment]
Fixed the error in the test case.  Warnings but it passed.  Would like to know reason for the failures.

[test_results.txt](https://github.com/enthought/pyql/files/156206/test_results.txt)

**Comment by dpinte** [comment]
I'll look into the details. From a quick review, can you confirm you build the QL DLL as explained in the doc? In particular the point 1 in this section https://github.com/enthought/pyql/blob/master/docs/source/getting_started.rst#installation-from-source-on-windows

**Comment by david-wolf** [comment]
Yes I did. Those steps seem to guarantee that if followed correctly the program will run - not its program correctness. 

I had some issues initially with the DEF file which prevented compilation but I went back and fixed that.

**Comment by david-wolf** [comment]
Note I used QL 1.7.1, MSVC 14 and Anaconda latest version with Python 3.5.

**Comment by david-wolf** [comment]
Full build output.
[build_output.txt](https://github.com/enthought/pyql/files/157056/build_output.txt)

**Comment by dpinte** [comment]
Thanks @dave-fl for the report. I'll investigate asap.

**Comment by bigtan** [comment]
[build_output.txt](https://github.com/enthought/pyql/files/179308/build_output.txt)

I got the similar output as @dave-fl, But I failed the comiling. The error log is listed in the txt file.

I used the nm from the mingw, maybe this the reason, or I should try cygwin?

**Comment by dpinte** [comment]
I think we should investigate  the https://github.com/enthought/pyql/blob/master/scripts/generate_symbols.py and check if it does its job correctly. It has been designed on Python 2.7 and known to work with Python 3.3. Python 3.5. is using a new Visual Studio version that might do things in a different way ...

**Comment by dave-fl** [comment]
I used cygwin.  Took a while to get the build going and then we had failed unit test cases.

**Comment by bigtan** [comment]
Hi @dpinte I use Python27 and vs2015, the .def file generated is just about 15mb. So I agree with you, Maybe something wrong with https://github.com/enthought/pyql/blob/master/scripts/generate_symbols.py

**Comment by ceaza** [comment]
H  @bigtan , it may be something to do with fact that Python27 is compiled using vs2008, and you are using vs2015. I can compile PyQl on WinPython3.5 but not on Python2.7 and I think this was my 2.7 issue. See   [https://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/].

So while I don't have much experience in this, all downstream module would also need to be compiled in vs2008.

**Comment by bigtan** [comment]
@ceaza I will try it on my laptop, and give the feedback here.

**Comment by dpinte** [comment]
@bigtan I confirme what @ceaza says. You must use the compatible MSVC version for the target Python. Python 2.7 means MSVC 2008.

**Comment by dpinte** [comment]
@bigtan another comment: it is expected that the def file is a big file...

**Comment by bigtan** [comment]
@dpinte I have finished the compiling for python 35 with MSVC2015, it works well.
I am now trying to compiling it for python 27 with MSVC2008

**Comment by dave-fl** [comment]
Is this active at all?

**Comment by dpinte** [comment]
@dave-fl I don't have much bandwidth at the moment. If you have some pressing needs and want to consider other options than contributor's free time, ping me by e-mail.
